[2022-12-11T14:23:43.153+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: songs1.ReadData scheduled__2022-12-10T00:00:00+00:00 [queued]>
[2022-12-11T14:23:43.164+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: songs1.ReadData scheduled__2022-12-10T00:00:00+00:00 [queued]>
[2022-12-11T14:23:43.164+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T14:23:43.165+0000] {taskinstance.py:1284} INFO - Starting attempt 28 of 33
[2022-12-11T14:23:43.165+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T14:23:43.176+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): ReadData> on 2022-12-10 00:00:00+00:00
[2022-12-11T14:23:43.183+0000] {standard_task_runner.py:55} INFO - Started process 7500 to run task
[2022-12-11T14:23:43.188+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'songs1', 'ReadData', 'scheduled__2022-12-10T00:00:00+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/song.py', '--cfg-path', '/tmp/tmpxo48e5z6']
[2022-12-11T14:23:43.196+0000] {standard_task_runner.py:83} INFO - Job 197: Subtask ReadData
[2022-12-11T14:23:43.281+0000] {task_command.py:389} INFO - Running <TaskInstance: songs1.ReadData scheduled__2022-12-10T00:00:00+00:00 [running]> on host 83e68f36074a
[2022-12-11T14:23:43.339+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gama Ariefsadya
AIRFLOW_CTX_DAG_ID=songs1
AIRFLOW_CTX_TASK_ID=ReadData
AIRFLOW_CTX_EXECUTION_DATE=2022-12-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=28
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-10T00:00:00+00:00
[2022-12-11T14:23:43.368+0000] {logging_mixin.py:137} INFO - <class 'dict'>
[2022-12-11T14:23:43.369+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/song.py", line 48, in ReadData
    print(json.dumps(song,4))
TypeError: dumps() takes 1 positional argument but 2 were given
[2022-12-11T14:23:43.396+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=songs1, task_id=ReadData, execution_date=20221210T000000, start_date=20221211T142343, end_date=20221211T142343
[2022-12-11T14:23:43.407+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 197 for task ReadData (dumps() takes 1 positional argument but 2 were given; 7500)
[2022-12-11T14:23:43.443+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-11T14:23:43.465+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
