[2022-12-11T14:19:01.524+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: songs1.ReadData scheduled__2022-12-10T00:00:00+00:00 [queued]>
[2022-12-11T14:19:01.531+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: songs1.ReadData scheduled__2022-12-10T00:00:00+00:00 [queued]>
[2022-12-11T14:19:01.531+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T14:19:01.532+0000] {taskinstance.py:1284} INFO - Starting attempt 23 of 28
[2022-12-11T14:19:01.532+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T14:19:01.540+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): ReadData> on 2022-12-10 00:00:00+00:00
[2022-12-11T14:19:01.544+0000] {standard_task_runner.py:55} INFO - Started process 7132 to run task
[2022-12-11T14:19:01.547+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'songs1', 'ReadData', 'scheduled__2022-12-10T00:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/song.py', '--cfg-path', '/tmp/tmpl04t4zm4']
[2022-12-11T14:19:01.552+0000] {standard_task_runner.py:83} INFO - Job 192: Subtask ReadData
[2022-12-11T14:19:01.608+0000] {task_command.py:389} INFO - Running <TaskInstance: songs1.ReadData scheduled__2022-12-10T00:00:00+00:00 [running]> on host 83e68f36074a
[2022-12-11T14:19:01.659+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gama Ariefsadya
AIRFLOW_CTX_DAG_ID=songs1
AIRFLOW_CTX_TASK_ID=ReadData
AIRFLOW_CTX_EXECUTION_DATE=2022-12-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=23
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-10T00:00:00+00:00
[2022-12-11T14:19:01.676+0000] {logging_mixin.py:137} INFO - <class 'dict'>
[2022-12-11T14:19:01.677+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/song.py", line 48, in ReadData
    print(json.dumps(song))
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Decimal is not JSON serializable
[2022-12-11T14:19:01.686+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=songs1, task_id=ReadData, execution_date=20221210T000000, start_date=20221211T141901, end_date=20221211T141901
[2022-12-11T14:19:01.693+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 192 for task ReadData (Object of type Decimal is not JSON serializable; 7132)
[2022-12-11T14:19:01.720+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-11T14:19:01.735+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
