[2022-12-11T14:01:07.319+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: songs1.ReadData scheduled__2022-12-10T00:00:00+00:00 [queued]>
[2022-12-11T14:01:07.326+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: songs1.ReadData scheduled__2022-12-10T00:00:00+00:00 [queued]>
[2022-12-11T14:01:07.327+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T14:01:07.327+0000] {taskinstance.py:1284} INFO - Starting attempt 9 of 14
[2022-12-11T14:01:07.328+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T14:01:07.337+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): ReadData> on 2022-12-10 00:00:00+00:00
[2022-12-11T14:01:07.342+0000] {standard_task_runner.py:55} INFO - Started process 5724 to run task
[2022-12-11T14:01:07.346+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'songs1', 'ReadData', 'scheduled__2022-12-10T00:00:00+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/song.py', '--cfg-path', '/tmp/tmp676k7vja']
[2022-12-11T14:01:07.351+0000] {standard_task_runner.py:83} INFO - Job 178: Subtask ReadData
[2022-12-11T14:01:07.405+0000] {task_command.py:389} INFO - Running <TaskInstance: songs1.ReadData scheduled__2022-12-10T00:00:00+00:00 [running]> on host 83e68f36074a
[2022-12-11T14:01:07.458+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gama Ariefsadya
AIRFLOW_CTX_DAG_ID=songs1
AIRFLOW_CTX_TASK_ID=ReadData
AIRFLOW_CTX_EXECUTION_DATE=2022-12-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=9
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-10T00:00:00+00:00
[2022-12-11T14:01:07.494+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/song.py", line 49, in ReadData
    songs=json.loads(songs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list
[2022-12-11T14:01:07.504+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=songs1, task_id=ReadData, execution_date=20221210T000000, start_date=20221211T140107, end_date=20221211T140107
[2022-12-11T14:01:07.512+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 178 for task ReadData (the JSON object must be str, bytes or bytearray, not list; 5724)
[2022-12-11T14:01:07.560+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-11T14:01:07.576+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
